package jp.toastkid.yobidashi4.presentation.editor.legacy

enum class MenuCommand {
    SAVE, PASTE_AS_QUOTATION, PASTE_LINK_WITH_TITLE, FIND, TO_TABLE, UNORDERED_LIST, ORDERED_LIST, TASK_LIST,
    ITALIC, BOLD, STRIKETHROUGH, BLOCKQUOTE, CODE_BLOCK, TRIMMING, FONT_COLOR, COUNT, WEB_SEARCH, DICTIONARY_SEARCH,
    TRANSLATION_TO_ENGLISH, HORIZONTAL_RULE, REVERSE_CASE, DUPLICATE_LINE, EXTRACT_LINE,
    TO_HYPERLINK, SWITCH_EDITABLE, REFRESH, OPEN_URL, SWITCH_WRAP_LINE, EDITOR_TO_TOP, EDITOR_TO_BOTTOM,
    SURROUND_BRACKET, SURROUND_JA_BRACKET, OPEN_WITH_BROWSER, URL_ENCODE, URL_DECODE
}